[build]
  base = "/"
  command = "pnpm install && pnpm build"
  publish = "dist/"
  
[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.4.1"
  NODE_ENV = "production"
[build.processing]
  skip_processing = false
# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS and Module Federation
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Special headers for remoteEntry.js (no cache)
[[headers]]
  for = "/remoteEntry.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "-1"
    Access-Control-Allow-Origin = "*"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
